# Generated by Django 5.0.7 on 2024-08-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqttapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MQTTMessage',
        ),
    ]
